/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author masha2470
 */
public class mathMethods extends javax.swing.JFrame {

    /**
     * Creates new form mathMethods
     */
    public mathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        largestLabel = new javax.swing.JLabel();
        largestnumber1 = new javax.swing.JTextField();
        largestnumber2 = new javax.swing.JTextField();
        largestButton = new javax.swing.JButton();
        smallestLabel = new javax.swing.JLabel();
        smallestButton = new javax.swing.JButton();
        smallestnumber3 = new javax.swing.JTextField();
        smallestnumber4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        powerDisplay5 = new javax.swing.JTextField();
        powernumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sideNumber6 = new javax.swing.JTextField();
        sideNumber7 = new javax.swing.JTextField();
        powerButton = new javax.swing.JButton();
        hypotenuseButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numberround8 = new javax.swing.JTextField();
        roundup9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        squareroot10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radians11 = new javax.swing.JTextField();
        rounddownbutton = new javax.swing.JButton();
        roundupbutton = new javax.swing.JButton();
        squarerootbutton = new javax.swing.JButton();
        radiansbutton = new javax.swing.JButton();
        labelDisplay1 = new javax.swing.JLabel();
        labelDisplay2 = new javax.swing.JLabel();
        labelDisplay3 = new javax.swing.JLabel();
        labelDisplay4 = new javax.swing.JLabel();
        labelDisplay5 = new javax.swing.JLabel();
        labelDisplay6 = new javax.swing.JLabel();
        labelDisplay7 = new javax.swing.JLabel();
        labelDisplay10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tittle.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        tittle.setText("Magical Math Methods ");

        largestLabel.setText("Enter two numbers and click the button. The program will display the largest of the two ");

        largestButton.setText("Largest");
        largestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largestButtonActionPerformed(evt);
            }
        });

        smallestLabel.setText("Enter two numbers and click the button. The program will display the smallest of the two ");

        smallestButton.setText("Smallest");
        smallestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallestButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter two numbers and click the button. The program will display the first number to the power of the second  ");

        powernumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powernumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter the length of two sides of a right angle triangle numbers and click the button. The program will display the hypotenuse  ");

        powerButton.setText("To the power of");
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });

        hypotenuseButton.setText("Hypotenuse");
        hypotenuseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotenuseButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter a decimal value. The program will display the value rounded down.");

        jLabel6.setText("Enter a decimal value. The program will display the value rounded up.");

        jLabel7.setText("Enter an integer. The program will display the square root of the integer  ");

        jLabel8.setText("Enter an angle in degrees. The program will display the angle in radians.");

        rounddownbutton.setText("Rounded Down");
        rounddownbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rounddownbuttonActionPerformed(evt);
            }
        });

        roundupbutton.setText("Rounded Up");
        roundupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundupbuttonActionPerformed(evt);
            }
        });

        squarerootbutton.setText("Square Root");
        squarerootbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squarerootbuttonActionPerformed(evt);
            }
        });

        radiansbutton.setText("In Radians");
        radiansbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiansbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(tittle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(largestnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(largestnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(largestButton)
                        .addGap(56, 56, 56)
                        .addComponent(labelDisplay1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(largestLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(smallestnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smallestnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(smallestButton)
                                .addGap(115, 115, 115)
                                .addComponent(labelDisplay2))
                            .addComponent(smallestLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(powerDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(powernumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(powerButton)
                        .addGap(69, 69, 69)
                        .addComponent(labelDisplay3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radians11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(radiansbutton)
                        .addGap(64, 64, 64)
                        .addComponent(labelDisplay10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(squareroot10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(squarerootbutton)
                        .addGap(41, 41, 41)
                        .addComponent(labelDisplay7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roundup9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(roundupbutton)
                        .addGap(50, 50, 50)
                        .addComponent(labelDisplay6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(sideNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(sideNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(hypotenuseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDisplay4))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numberround8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(rounddownbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDisplay5))
                            .addComponent(jLabel6))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tittle)
                .addGap(18, 18, 18)
                .addComponent(largestLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(largestnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(largestnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(largestButton))
                    .addComponent(labelDisplay1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(smallestnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(smallestnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(smallestButton))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(powerDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(powernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(powerButton)
                                    .addComponent(labelDisplay3))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sideNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sideNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hypotenuseButton)
                                    .addComponent(labelDisplay4))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberround8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rounddownbutton)
                                    .addComponent(labelDisplay5))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roundup9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roundupbutton)
                                    .addComponent(labelDisplay6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(squareroot10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(squarerootbutton)
                                    .addComponent(labelDisplay7))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(smallestLabel)
                                .addGap(18, 18, 18)
                                .addComponent(labelDisplay2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radians11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiansbutton)))
                    .addComponent(labelDisplay10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void largestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largestButtonActionPerformed
     double number1 = Double.parseDouble(largestnumber1.getText());  
     double number2 = Double.parseDouble(largestnumber2.getText());
     labelDisplay1.setText("The largest number is " + Math.max(number1,number2));
     
       
    
        
    }//GEN-LAST:event_largestButtonActionPerformed

    private void smallestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallestButtonActionPerformed
     double number3 = Double.parseDouble(smallestnumber3.getText());  
     double number4 = Double.parseDouble(smallestnumber4.getText());
     labelDisplay2.setText("The smallest number is " + Math.min(number3,number4));   
    }//GEN-LAST:event_smallestButtonActionPerformed

    private void powernumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powernumberActionPerformed
       
    }//GEN-LAST:event_powernumberActionPerformed

    private void hypotenuseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotenuseButtonActionPerformed
     double number6 = Double.parseDouble(sideNumber6.getText());  
     double number7 = Double.parseDouble(sideNumber7.getText());
     labelDisplay4.setText("The hypotenuse is " + Math.hypot(number6,number7));   
    }//GEN-LAST:event_hypotenuseButtonActionPerformed

    private void rounddownbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rounddownbuttonActionPerformed
      double number8 = Double.parseDouble(numberround8.getText());  
     labelDisplay5.setText("The number rounded down is " + Math.floor(number8));     
    }//GEN-LAST:event_rounddownbuttonActionPerformed

    private void squarerootbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squarerootbuttonActionPerformed
         double number10 = Double.parseDouble(squareroot10.getText());  
     labelDisplay7.setText("The number's squareroot is" +  Math.sqrt(number10));
    }//GEN-LAST:event_squarerootbuttonActionPerformed

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerButtonActionPerformed
     double number5 = Double.parseDouble(powerDisplay5.getText());  
     double number6 = Double.parseDouble(powernumber.getText());
     labelDisplay3.setText("The number is" +  Math.pow(number5, number6));
    }//GEN-LAST:event_powerButtonActionPerformed

    private void roundupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundupbuttonActionPerformed
    double number9 = Double.parseDouble(roundup9.getText());  
     labelDisplay6.setText("The number rounded up is" +  Math.ceil(number9));
    }//GEN-LAST:event_roundupbuttonActionPerformed

    private void radiansbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiansbuttonActionPerformed
     double number11 = Double.parseDouble(radians11.getText());  
     labelDisplay10.setText("The number in radians is" +  Math.toRadians(number11));  
    }//GEN-LAST:event_radiansbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hypotenuseButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDisplay1;
    private javax.swing.JLabel labelDisplay10;
    private javax.swing.JLabel labelDisplay2;
    private javax.swing.JLabel labelDisplay3;
    private javax.swing.JLabel labelDisplay4;
    private javax.swing.JLabel labelDisplay5;
    private javax.swing.JLabel labelDisplay6;
    private javax.swing.JLabel labelDisplay7;
    private javax.swing.JButton largestButton;
    private javax.swing.JLabel largestLabel;
    private javax.swing.JTextField largestnumber1;
    private javax.swing.JTextField largestnumber2;
    private javax.swing.JTextField numberround8;
    private javax.swing.JButton powerButton;
    private javax.swing.JTextField powerDisplay5;
    private javax.swing.JTextField powernumber;
    private javax.swing.JTextField radians11;
    private javax.swing.JButton radiansbutton;
    private javax.swing.JButton rounddownbutton;
    private javax.swing.JTextField roundup9;
    private javax.swing.JButton roundupbutton;
    private javax.swing.JTextField sideNumber6;
    private javax.swing.JTextField sideNumber7;
    private javax.swing.JButton smallestButton;
    private javax.swing.JLabel smallestLabel;
    private javax.swing.JTextField smallestnumber3;
    private javax.swing.JTextField smallestnumber4;
    private javax.swing.JTextField squareroot10;
    private javax.swing.JButton squarerootbutton;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
